[project]
name = "hackernews"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "grequests>=0.7.0",
    "thefuzz>=0.22.1",
]
